#!/bin/sh
# drun-popos
# Pop!_OS / rounded style app launcher

if pgrep -f '(^|/)wofi( |$)' >/dev/null 2>&1; then
    pkill -f '(^|/)wofi( |$)'
    exit 0
fi

exec wofi \
    --conf "$HOME/.config/wofi/config-popos" \
    --style "$HOME/.config/wofi/style-popos.css" \
    --show drun
